package prog2.vista;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import prog2.model.Dades;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AppCentralUB extends JFrame {
    private JPanel panel1;
    private JButton btnGestioComponentsCentral;
    private JLabel lblDia;
    private JLabel lblDemanda;
    private JLabel lblGuanys;
    private JButton btnFinalitzaDia;
    Dades dades;
    CentralUB centralUB;


    public AppCentralUB() throws CentralUBException {
        this.dades = new Dades();           // Inicialitzem l'objecte
        this.centralUB = new CentralUB();   // Suposant que tens un constructor per defecte

        $$$setupUI$$$(); // Afegeix-ho si no hi és explícitament

        setTitle("Central UB");
        setSize(1000, 650);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setContentPane(panel1);

        // Inicialitza les etiquetes amb valors actuals
        lblDia.setText("Dia: " + dades.getDia());
        lblGuanys.setText("Guanys: " + dades.getGuanysAcumulats());
        lblDemanda.setText("Demanda: " + centralUB.getDemandaPotencia());

        // Botó per obrir la finestra de gestió de components
        btnGestioComponentsCentral.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FrmGestioComponentsCentral dialog = new FrmGestioComponentsCentral(AppCentralUB.this, dades);
                dialog.setVisible(true);
            }
        });
        btnFinalitzaDia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dades.finalitzaDia(centralUB.getDemandaPotencia());
                centralUB.finalitzaDia();
                actualitzaLables();
            }
        });
    }
    public void actualitzaLables() {
        lblDia.setText("Dia: " + dades.getDia());
        lblDemanda.setText("Demanda: " + centralUB.getDemandaPotencia());
        lblGuanys.setText("Guanys: " + dades.getGuanysAcumulats());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnGestioComponentsCentral = new JButton();
        btnGestioComponentsCentral.setText("Gestionar Central");
        panel2.add(btnGestioComponentsCentral, new GridConstraints(0, 0, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 60), new Dimension(600, 60), 0, false));
        lblDia = new JLabel();
        lblDia.setText("Dia: " + dades.getDia());
        panel2.add(lblDia, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblDemanda = new JLabel();
        lblDemanda.setText("Demanda: ");
        panel2.add(lblDemanda, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblGuanys = new JLabel();
        lblGuanys.setText("Guanys:");
        panel2.add(lblGuanys, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        btnFinalitzaDia = new JButton();
        btnFinalitzaDia.setText("Finalitza Dia");
        panel2.add(btnFinalitzaDia, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
